### ISSUE TITLE
Getting the context clue comments with the strings

### ISSUE THREAD

**Issue by juanpaco** [justinklemm/i18n-strings-files#5]
Do you have any interest in getting the comments that sit above a key-value pair in the return data?

I'm building a tool to let volunteers translate strings in a file, and I'd like to be able to display those context comments in the tool as well as the keys and values.  I'm happy to do the work on this if you're interested in having it.

It seems like this is something to put in the `parse` function at first perusal.

If you'd like me to add this, did you author this in coffee script?

**Comment by justinklemm** [comment]
@juanpaco, this isn't something I specifically need, but you're more than welcome to code it up and submit a PR for it. I'm a little concerned about adding it to the existing `parse()` function because that currently returns an object containing the key/value pairs; I'm not sure how the comment data would be organized within that existing format... A better approach may be to add a separate `parseWithComments()` function -- that way you could return a new type of data structure better suited to your needs situation. For example:

```
[
  {
    "key-name": {
      "value": "value here",
      "comments": "associated comments"
    }
  },
  ...
]
```

Yes, the package is written in CoffeeScript. The code lives in `index.coffee`. If you intend to submit a PR, please author it in CoffeeScript and include tests for your features in `test/test.coffee`.

**Comment by justinklemm** [comment]
@juanpaco Following up here. I believe this was added in PR #6 and should be live in the latest package. I'm closing this issue. Feel free to reopen if they updates don't suit your needs.
